# Generated by Django 3.2.6 on 2021-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210827_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='objects')),
                ('is_active', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
    ]
